apiVersion: v1
kind: ConfigMap
metadata:
  namespace: base
  labels:
    app: gitlab-deployer
  name: gitlab-runner-cm
data:
  REGISTER_NON_INTERACTIVE: "true"
  REGISTER_LOCKED: "false"
  CI_SERVER_URL: "http://gitlab.web/"
  METRICS_SERVER: "0.0.0.0:9100"
  RUNNER_CONCURRENT_BUILDS: "4"
  RUNNER_REQUEST_CONCURRENCY: "4"
  RUNNER_TAG_LIST: "kubernetes,gitlab-runner"
  RUNNER_EXECUTOR: "kubernetes"
  KUBERNETES_NAMESPACE: "base"
  KUBERNETES_SERVICE_ACCOUNT: "executor"
  KUBERNETES_PULL_POLICY: "if-not-present"