apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jenkins
  namespace: base
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: jenkins.web
    http:
      paths:
      - path: /
        backend:
          serviceName: jenkins.base
          servicePort: 8080