apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mongo
  namespace: base
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: mongo.web
    http:
      paths:
      - path: /
        backend:
          serviceName: mongo
          servicePort: 27017